### ISSUE TITLE
Support for Kerberos Tickets with SSH Client (GSSAPI Authentication)

### ISSUE THREAD

**Issue by jkonvicka** [tmds/Tmds.Ssh#257]
Hi @tmds,

I’m working on a use case that requires using `Tmds.Ssh` to establish an SSH connection with Kerberos authentication (GSSAPI). In this scenario:

- The Kerberos ticket is provided as a file by an external provider.
- I need to "import" or use this ticket with the SSH client to authenticate against the target external VM/service.

Could you guide me on whether `Tmds.Ssh` supports such a setup? If yes, could you provide an example or explain the steps to:

1. Load the Kerberos ticket from a file.
2. Use the ticket to establish an SSH connection using GSSAPI.

If this functionality isn't currently supported, are there any plans or workarounds you’d recommend?

Thank you for your great work on this library, and I appreciate your time!

Best regards,  
Jakub Konvicka

Execution of this code ends with `An error occurred: The connection could not be established - AuthenticationFailed - Authentication failed.`.

#### Unconfigured example:
```csharp
using Tmds.Ssh;

class Program
{
    static async Task Main(string[] args)
    {
        // Set the `KRB5CCNAME` environment variable for the Kerberos library to locate the ticket
        //Environment.SetEnvironmentVariable("KRB5_CONFIG", "/etc/krb5.conf");
        Environment.SetEnvironmentVariable("KRB5CCNAME", "FILE:/path/to/kerberos/ticket/file");

        string userName = "username";
        var settings = new SshClientSettings("server")
        {
          
            UserName = userName,
            Credentials = [ new KerberosCredential() ],
        };

        using var client = new SshClient(settings);

        try
        {
            // Connect to the SSH client
            await client.ConnectAsync();

            // Execute the "whoami" command
            using var process = await client.ExecuteAsync("whoami");
            (string? stdout, string? stderr) = await process.ReadToEndAsStringAsync();

            Console.WriteLine($"stdout: {stdout}");
            if (!string.IsNullOrEmpty(stderr))
            {
                Console.WriteLine($"stderr: {stderr}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"An error occurred: {ex.Message}");
        }
    }
}

```

**Comment by jkonvicka** [comment]
@tmds 

Thank you for your quick reply. 

Yes, I’ve tested the OpenSSH `ssh` command with GSSAPI before trying it out with `TMDS.SSH`, and it worked. I also tested using a Kerberos ticket loaded via the `kinit` command natively in the terminal. Without specifying the `ccache` file path (meaning it was loaded into the API ccache as described in the [Kerberos documentation](https://web.mit.edu/kerberos/krb5-1.12/doc/basic/ccache_def.html)), it also worked with `TMDS.SSH` (as shown in the code snippet in the original message above).

However, the issue lies in the configuration of the `TMDS.SSH` client. Specifically, I am unsure how to configure the `KRB5CCNAME` environment variable (or a different attribute in `TMDS.SSH`) to pass a Kerberos ticket stored in the `DIR` or `FILE` Kerberos ccache type.

**Comment by jborean93** [comment]
> However, the issue lies in the configuration of the TMDS.SSH client. Specifically, I am unsure how to configure the KRB5CCNAME environment variable (or a different attribute in TMDS.SSH) to pass a Kerberos ticket stored in the DIR or FILE Kerberos ccache type.

Tmds.Ssh (through .NET) just calls the underlying Kerberos C library which is the one that handles all the various Kerberos env vars and ticket loading behaviour. This C API works just fine with things like `KRB5CCNAME`, `KRB5_KTNAME`, `KRB5_CONFIG`, etc but the problem here is around the behaviour of env vars and .NET itself.

When .NET starts a process on non-Windows it takes a snapshot of the process environment block. Any changes at runtime to the process env throughs through `Environment.SetEnvironmentVariable` will edit that cached .NET block and won't actually change the process env block. This is a problem when calling C libraries as it still reads from the process env block and not the one managed by the .NET runtime. If .NET was to start a new process then it will use the .NET cached values but once it has started then it won't change the process native env block.

The few things you can do is

+ Ensure you start the process with `KRB5CCNAME` or other relevant env vars already set so that the native process env block has it set and the Kerberos C libs can see them, or
+ Use PInvoke to call [setenv](https://man7.org/linux/man-pages/man3/setenv.3.html) manually to edit the native env block

**Comment by tmds** [comment]
@jkonvicka as Jordan points out, changes made through `Environment.SetEnvironmentVariable` won't be picked up by the C library used under the hood.

The simplest is if you can set the envvar before starting the application.

PInvoke of `setenv` may come with thread-safety issues.

Another option may be to let your app start itself again with the envvar set. https://github.com/tmds/Tmds.ExecFunction can help do that.

**Comment by tmds** [comment]
@jkonvicka I think we identified the root cause. Can this issue be closed?

**Comment by jkonvicka** [comment]
@tmds yes, thank you. When I set the `env` variable before the application started and it works.
